### PR TITLE
Fixed Faction Leader Study Bug & Increased Gate Lore Weight

### PR DESCRIPTION
**Pull request by Mochnant**
- Increased Gate Lore weight at level 1 to 35 (was 15) and level 2 to 150 (was 100).
- Fixed bug with Faction Leaders that prevented study.

### CODE REVIEW

**Review by nedbrek — COMMENTED** [review]
Does it need to be 32 with staff and robe? Maybe 35 or 40?

**Comment by Mochnant** [comment]
```Errors during turn:
Unit (170): GIVE: Can't mix leaders and normal men.
Unit (170): GIVE: Can't mix leaders and normal men.```

Non-mage LEADERS and FACTION LEADERS can mix, but neither can mix with non-leader men.

**Comment by Mochnant** [comment]
Yeah, you're right.  40 seems too high considering the level 2 is only 100.

So we want to boost level 2?  35 and 150?

**Comment by nedbrek** [comment]
Yeah, the gate lore and portal lore weights are crazy low. PORT 4 allows like 200#

**Comment by Mochnant** [comment]
@nedbrek Weights boosted.

**Pull request merged**
